### ISSUE TITLE
傷害欄位調整想法

### ISSUE THREAD

**Issue by BrandonTing** [Klay376014/Calculator-2024ver#18]
- Attacker/Defender文案可能有點混淆：右側可以切換攻擊方但是Defender/Attacker的顯示不會變，雖然那兩個icon滿好看的但不確定會不會造成誤會
- stopWatch -> 按了之後如果switch成resume watch 感覺會好懂很多
-

**Comment by Klay376014** [comment]
Attacker/Defender: 有在考慮換成其他文字/icon，不知道有沒有什麼好建議(不過預設還是左打右)

stopWatch -> 按了之後如果switch成resume watch → 好像不錯 可以再改(stop / play之類的icon)
